# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(587, 519)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblParametros = QtGui.QLabel(self.centralWidget)
        self.lblParametros.setObjectName(_fromUtf8("lblParametros"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblParametros)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblClasse = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClasse.sizePolicy().hasHeightForWidth())
        self.lblClasse.setSizePolicy(sizePolicy)
        self.lblClasse.setObjectName(_fromUtf8("lblClasse"))
        self.horizontalLayout.addWidget(self.lblClasse)
        self.cmbClasse = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClasse.sizePolicy().hasHeightForWidth())
        self.cmbClasse.setSizePolicy(sizePolicy)
        self.cmbClasse.setObjectName(_fromUtf8("cmbClasse"))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbClasse)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblFolhas = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolhas.sizePolicy().hasHeightForWidth())
        self.lblFolhas.setSizePolicy(sizePolicy)
        self.lblFolhas.setObjectName(_fromUtf8("lblFolhas"))
        self.verticalLayout_2.addWidget(self.lblFolhas)
        self.lblOrdem = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrdem.sizePolicy().hasHeightForWidth())
        self.lblOrdem.setSizePolicy(sizePolicy)
        self.lblOrdem.setObjectName(_fromUtf8("lblOrdem"))
        self.verticalLayout_2.addWidget(self.lblOrdem)
        self.lblDiametro = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiametro.sizePolicy().hasHeightForWidth())
        self.lblDiametro.setSizePolicy(sizePolicy)
        self.lblDiametro.setObjectName(_fromUtf8("lblDiametro"))
        self.verticalLayout_2.addWidget(self.lblDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFolhas = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFolhas.sizePolicy().hasHeightForWidth())
        self.edtFolhas.setSizePolicy(sizePolicy)
        self.edtFolhas.setObjectName(_fromUtf8("edtFolhas"))
        self.verticalLayout.addWidget(self.edtFolhas)
        self.edtOrdem = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOrdem.sizePolicy().hasHeightForWidth())
        self.edtOrdem.setSizePolicy(sizePolicy)
        self.edtOrdem.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.edtOrdem.setObjectName(_fromUtf8("edtOrdem"))
        self.verticalLayout.addWidget(self.edtOrdem)
        self.edtDiametro = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiametro.sizePolicy().hasHeightForWidth())
        self.edtDiametro.setSizePolicy(sizePolicy)
        self.edtDiametro.setObjectName(_fromUtf8("edtDiametro"))
        self.verticalLayout.addWidget(self.edtDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.formLayout.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.btnGerarTabela = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerarTabela.sizePolicy().hasHeightForWidth())
        self.btnGerarTabela.setSizePolicy(sizePolicy)
        self.btnGerarTabela.setObjectName(_fromUtf8("btnGerarTabela"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnGerarTabela)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.lblFolhas.setBuddy(self.edtFolhas)
        self.lblOrdem.setBuddy(self.edtOrdem)
        self.lblDiametro.setBuddy(self.edtDiametro)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblParametros.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Parâmetros</span></p></body></html>", None))
        self.lblClasse.setText(_translate("MainWindow", "Classe:", None))
        self.cmbClasse.setItemText(0, _translate("MainWindow", "Double Broom", None))
        self.cmbClasse.setItemText(1, _translate("MainWindow", "Broom", None))
        self.lblFolhas.setText(_translate("MainWindow", "Folhas (k):", None))
        self.lblOrdem.setText(_translate("MainWindow", "Ordem (n):", None))
        self.lblDiametro.setText(_translate("MainWindow", "Diâmetro (d):", None))
        self.btnGerarTabela.setText(_translate("MainWindow", "Gerar Tabela...", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(587, 519)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblParametros = QtGui.QLabel(self.centralWidget)
        self.lblParametros.setObjectName(_fromUtf8("lblParametros"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblParametros)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblClasse = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClasse.sizePolicy().hasHeightForWidth())
        self.lblClasse.setSizePolicy(sizePolicy)
        self.lblClasse.setObjectName(_fromUtf8("lblClasse"))
        self.horizontalLayout.addWidget(self.lblClasse)
        self.cmbClasse = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClasse.sizePolicy().hasHeightForWidth())
        self.cmbClasse.setSizePolicy(sizePolicy)
        self.cmbClasse.setObjectName(_fromUtf8("cmbClasse"))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbClasse)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblFolhas = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolhas.sizePolicy().hasHeightForWidth())
        self.lblFolhas.setSizePolicy(sizePolicy)
        self.lblFolhas.setObjectName(_fromUtf8("lblFolhas"))
        self.verticalLayout_2.addWidget(self.lblFolhas)
        self.lblOrdem = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrdem.sizePolicy().hasHeightForWidth())
        self.lblOrdem.setSizePolicy(sizePolicy)
        self.lblOrdem.setObjectName(_fromUtf8("lblOrdem"))
        self.verticalLayout_2.addWidget(self.lblOrdem)
        self.lblDiametro = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiametro.sizePolicy().hasHeightForWidth())
        self.lblDiametro.setSizePolicy(sizePolicy)
        self.lblDiametro.setObjectName(_fromUtf8("lblDiametro"))
        self.verticalLayout_2.addWidget(self.lblDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFolhas = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFolhas.sizePolicy().hasHeightForWidth())
        self.edtFolhas.setSizePolicy(sizePolicy)
        self.edtFolhas.setObjectName(_fromUtf8("edtFolhas"))
        self.verticalLayout.addWidget(self.edtFolhas)
        self.edtOrdem = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOrdem.sizePolicy().hasHeightForWidth())
        self.edtOrdem.setSizePolicy(sizePolicy)
        self.edtOrdem.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.edtOrdem.setObjectName(_fromUtf8("edtOrdem"))
        self.verticalLayout.addWidget(self.edtOrdem)
        self.edtDiametro = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiametro.sizePolicy().hasHeightForWidth())
        self.edtDiametro.setSizePolicy(sizePolicy)
        self.edtDiametro.setObjectName(_fromUtf8("edtDiametro"))
        self.verticalLayout.addWidget(self.edtDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.formLayout.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.btnGerarTabela = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerarTabela.sizePolicy().hasHeightForWidth())
        self.btnGerarTabela.setSizePolicy(sizePolicy)
        self.btnGerarTabela.setObjectName(_fromUtf8("btnGerarTabela"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnGerarTabela)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.lblFolhas.setBuddy(self.edtFolhas)
        self.lblOrdem.setBuddy(self.edtOrdem)
        self.lblDiametro.setBuddy(self.edtDiametro)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblParametros.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Parâmetros</span></p></body></html>", None))
        self.lblClasse.setText(_translate("MainWindow", "Classe:", None))
        self.cmbClasse.setItemText(0, _translate("MainWindow", "Double Broom", None))
        self.cmbClasse.setItemText(1, _translate("MainWindow", "Broom", None))
        self.lblFolhas.setText(_translate("MainWindow", "Folhas (k):", None))
        self.lblOrdem.setText(_translate("MainWindow", "Ordem (n):", None))
        self.lblDiametro.setText(_translate("MainWindow", "Diâmetro (d):", None))
        self.btnGerarTabela.setText(_translate("MainWindow", "Gerar Tabela...", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(587, 519)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblParametros = QtGui.QLabel(self.centralWidget)
        self.lblParametros.setObjectName(_fromUtf8("lblParametros"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblParametros)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblClasse = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClasse.sizePolicy().hasHeightForWidth())
        self.lblClasse.setSizePolicy(sizePolicy)
        self.lblClasse.setObjectName(_fromUtf8("lblClasse"))
        self.horizontalLayout.addWidget(self.lblClasse)
        self.cmbClasse = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClasse.sizePolicy().hasHeightForWidth())
        self.cmbClasse.setSizePolicy(sizePolicy)
        self.cmbClasse.setObjectName(_fromUtf8("cmbClasse"))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbClasse)
        self.formLayout.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblFolhas = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolhas.sizePolicy().hasHeightForWidth())
        self.lblFolhas.setSizePolicy(sizePolicy)
        self.lblFolhas.setObjectName(_fromUtf8("lblFolhas"))
        self.verticalLayout_2.addWidget(self.lblFolhas)
        self.lblOrdem = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrdem.sizePolicy().hasHeightForWidth())
        self.lblOrdem.setSizePolicy(sizePolicy)
        self.lblOrdem.setObjectName(_fromUtf8("lblOrdem"))
        self.verticalLayout_2.addWidget(self.lblOrdem)
        self.lblDiametro = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiametro.sizePolicy().hasHeightForWidth())
        self.lblDiametro.setSizePolicy(sizePolicy)
        self.lblDiametro.setObjectName(_fromUtf8("lblDiametro"))
        self.verticalLayout_2.addWidget(self.lblDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFolhas = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFolhas.sizePolicy().hasHeightForWidth())
        self.edtFolhas.setSizePolicy(sizePolicy)
        self.edtFolhas.setObjectName(_fromUtf8("edtFolhas"))
        self.verticalLayout.addWidget(self.edtFolhas)
        self.edtOrdem = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOrdem.sizePolicy().hasHeightForWidth())
        self.edtOrdem.setSizePolicy(sizePolicy)
        self.edtOrdem.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.edtOrdem.setObjectName(_fromUtf8("edtOrdem"))
        self.verticalLayout.addWidget(self.edtOrdem)
        self.edtDiametro = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiametro.sizePolicy().hasHeightForWidth())
        self.edtDiametro.setSizePolicy(sizePolicy)
        self.edtDiametro.setObjectName(_fromUtf8("edtDiametro"))
        self.verticalLayout.addWidget(self.edtDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAdicionarAresta = QtGui.QPushButton(self.centralWidget)
        self.btnAdicionarAresta.setObjectName(_fromUtf8("btnAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.btnAdicionarAresta)
        self.edtAdicionarAresta = QtGui.QLineEdit(self.centralWidget)
        self.edtAdicionarAresta.setObjectName(_fromUtf8("edtAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.edtAdicionarAresta)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.btnGerarTabela = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerarTabela.sizePolicy().hasHeightForWidth())
        self.btnGerarTabela.setSizePolicy(sizePolicy)
        self.btnGerarTabela.setObjectName(_fromUtf8("btnGerarTabela"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnGerarTabela)
        self.btnGerarGrafo = QtGui.QPushButton(self.centralWidget)
        self.btnGerarGrafo.setObjectName(_fromUtf8("btnGerarGrafo"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.btnGerarGrafo)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.lblFolhas.setBuddy(self.edtFolhas)
        self.lblOrdem.setBuddy(self.edtOrdem)
        self.lblDiametro.setBuddy(self.edtDiametro)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblParametros.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Parâmetros</span></p></body></html>", None))
        self.lblClasse.setText(_translate("MainWindow", "Classe:", None))
        self.cmbClasse.setItemText(0, _translate("MainWindow", "Double Broom", None))
        self.cmbClasse.setItemText(1, _translate("MainWindow", "Broom", None))
        self.lblFolhas.setText(_translate("MainWindow", "Folhas (k):", None))
        self.lblOrdem.setText(_translate("MainWindow", "Ordem (n):", None))
        self.lblDiametro.setText(_translate("MainWindow", "Diâmetro (d):", None))
        self.btnAdicionarAresta.setText(_translate("MainWindow", "Adicionar Aresta", None))
        self.btnGerarTabela.setText(_translate("MainWindow", "Gerar Tabela...", None))
        self.btnGerarGrafo.setText(_translate("MainWindow", "Gerar Grafo", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(524, 460)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.centralWidget)
        self.formLayout_2.setMargin(11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblParametros = QtGui.QLabel(self.centralWidget)
        self.lblParametros.setObjectName(_fromUtf8("lblParametros"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblParametros)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblClasse = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClasse.sizePolicy().hasHeightForWidth())
        self.lblClasse.setSizePolicy(sizePolicy)
        self.lblClasse.setObjectName(_fromUtf8("lblClasse"))
        self.horizontalLayout.addWidget(self.lblClasse)
        self.cmbClasse = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClasse.sizePolicy().hasHeightForWidth())
        self.cmbClasse.setSizePolicy(sizePolicy)
        self.cmbClasse.setObjectName(_fromUtf8("cmbClasse"))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbClasse)
        self.formLayout.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblFolhas = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolhas.sizePolicy().hasHeightForWidth())
        self.lblFolhas.setSizePolicy(sizePolicy)
        self.lblFolhas.setObjectName(_fromUtf8("lblFolhas"))
        self.verticalLayout_2.addWidget(self.lblFolhas)
        self.lblOrdem = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrdem.sizePolicy().hasHeightForWidth())
        self.lblOrdem.setSizePolicy(sizePolicy)
        self.lblOrdem.setObjectName(_fromUtf8("lblOrdem"))
        self.verticalLayout_2.addWidget(self.lblOrdem)
        self.lblDiametro = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiametro.sizePolicy().hasHeightForWidth())
        self.lblDiametro.setSizePolicy(sizePolicy)
        self.lblDiametro.setObjectName(_fromUtf8("lblDiametro"))
        self.verticalLayout_2.addWidget(self.lblDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFolhas = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFolhas.sizePolicy().hasHeightForWidth())
        self.edtFolhas.setSizePolicy(sizePolicy)
        self.edtFolhas.setObjectName(_fromUtf8("edtFolhas"))
        self.verticalLayout.addWidget(self.edtFolhas)
        self.edtOrdem = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOrdem.sizePolicy().hasHeightForWidth())
        self.edtOrdem.setSizePolicy(sizePolicy)
        self.edtOrdem.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.edtOrdem.setObjectName(_fromUtf8("edtOrdem"))
        self.verticalLayout.addWidget(self.edtOrdem)
        self.edtDiametro = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiametro.sizePolicy().hasHeightForWidth())
        self.edtDiametro.setSizePolicy(sizePolicy)
        self.edtDiametro.setObjectName(_fromUtf8("edtDiametro"))
        self.verticalLayout.addWidget(self.edtDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAdicionarAresta = QtGui.QPushButton(self.centralWidget)
        self.btnAdicionarAresta.setObjectName(_fromUtf8("btnAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.btnAdicionarAresta)
        self.edtAdicionarAresta = QtGui.QLineEdit(self.centralWidget)
        self.edtAdicionarAresta.setObjectName(_fromUtf8("edtAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.edtAdicionarAresta)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.btnGerarTabela = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerarTabela.sizePolicy().hasHeightForWidth())
        self.btnGerarTabela.setSizePolicy(sizePolicy)
        self.btnGerarTabela.setObjectName(_fromUtf8("btnGerarTabela"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnGerarTabela)
        self.btnGerarGrafo = QtGui.QPushButton(self.centralWidget)
        self.btnGerarGrafo.setObjectName(_fromUtf8("btnGerarGrafo"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.btnGerarGrafo)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.lblFolhas.setBuddy(self.edtFolhas)
        self.lblOrdem.setBuddy(self.edtOrdem)
        self.lblDiametro.setBuddy(self.edtDiametro)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblParametros.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Parâmetros</span></p></body></html>", None))
        self.lblClasse.setText(_translate("MainWindow", "Classe:", None))
        self.cmbClasse.setItemText(0, _translate("MainWindow", "Double Broom", None))
        self.cmbClasse.setItemText(1, _translate("MainWindow", "Broom", None))
        self.lblFolhas.setText(_translate("MainWindow", "Folhas (k):", None))
        self.lblOrdem.setText(_translate("MainWindow", "Ordem (n):", None))
        self.lblDiametro.setText(_translate("MainWindow", "Diâmetro (d):", None))
        self.btnAdicionarAresta.setText(_translate("MainWindow", "Adicionar Aresta", None))
        self.btnGerarTabela.setText(_translate("MainWindow", "Gerar Tabela...", None))
        self.btnGerarGrafo.setText(_translate("MainWindow", "Gerar Grafo", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 448)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblParametros = QtGui.QLabel(self.centralWidget)
        self.lblParametros.setObjectName(_fromUtf8("lblParametros"))
        self.gridLayout.addWidget(self.lblParametros, 0, 0, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 2, 4, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblClasse = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClasse.sizePolicy().hasHeightForWidth())
        self.lblClasse.setSizePolicy(sizePolicy)
        self.lblClasse.setObjectName(_fromUtf8("lblClasse"))
        self.horizontalLayout.addWidget(self.lblClasse)
        self.cmbClasse = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClasse.sizePolicy().hasHeightForWidth())
        self.cmbClasse.setSizePolicy(sizePolicy)
        self.cmbClasse.setObjectName(_fromUtf8("cmbClasse"))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.cmbClasse.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbClasse)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblFolhas = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFolhas.sizePolicy().hasHeightForWidth())
        self.lblFolhas.setSizePolicy(sizePolicy)
        self.lblFolhas.setObjectName(_fromUtf8("lblFolhas"))
        self.verticalLayout_2.addWidget(self.lblFolhas)
        self.lblOrdem = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrdem.sizePolicy().hasHeightForWidth())
        self.lblOrdem.setSizePolicy(sizePolicy)
        self.lblOrdem.setObjectName(_fromUtf8("lblOrdem"))
        self.verticalLayout_2.addWidget(self.lblOrdem)
        self.lblDiametro = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiametro.sizePolicy().hasHeightForWidth())
        self.lblDiametro.setSizePolicy(sizePolicy)
        self.lblDiametro.setObjectName(_fromUtf8("lblDiametro"))
        self.verticalLayout_2.addWidget(self.lblDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFolhas = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFolhas.sizePolicy().hasHeightForWidth())
        self.edtFolhas.setSizePolicy(sizePolicy)
        self.edtFolhas.setObjectName(_fromUtf8("edtFolhas"))
        self.verticalLayout.addWidget(self.edtFolhas)
        self.edtOrdem = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOrdem.sizePolicy().hasHeightForWidth())
        self.edtOrdem.setSizePolicy(sizePolicy)
        self.edtOrdem.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.edtOrdem.setObjectName(_fromUtf8("edtOrdem"))
        self.verticalLayout.addWidget(self.edtOrdem)
        self.edtDiametro = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiametro.sizePolicy().hasHeightForWidth())
        self.edtDiametro.setSizePolicy(sizePolicy)
        self.edtDiametro.setObjectName(_fromUtf8("edtDiametro"))
        self.verticalLayout.addWidget(self.edtDiametro)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAdicionarAresta = QtGui.QPushButton(self.centralWidget)
        self.btnAdicionarAresta.setObjectName(_fromUtf8("btnAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.btnAdicionarAresta)
        self.edtAdicionarAresta = QtGui.QLineEdit(self.centralWidget)
        self.edtAdicionarAresta.setObjectName(_fromUtf8("edtAdicionarAresta"))
        self.horizontalLayout_3.addWidget(self.edtAdicionarAresta)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 2)
        self.btnGerarTabela = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerarTabela.sizePolicy().hasHeightForWidth())
        self.btnGerarTabela.setSizePolicy(sizePolicy)
        self.btnGerarTabela.setObjectName(_fromUtf8("btnGerarTabela"))
        self.gridLayout.addWidget(self.btnGerarTabela, 3, 0, 1, 1)
        self.btnGerarGrafo = QtGui.QPushButton(self.centralWidget)
        self.btnGerarGrafo.setObjectName(_fromUtf8("btnGerarGrafo"))
        self.gridLayout.addWidget(self.btnGerarGrafo, 3, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.lblFolhas.setBuddy(self.edtFolhas)
        self.lblOrdem.setBuddy(self.edtOrdem)
        self.lblDiametro.setBuddy(self.edtDiametro)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblParametros.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Parâmetros</span></p></body></html>", None))
        self.lblClasse.setText(_translate("MainWindow", "Classe:", None))
        self.cmbClasse.setItemText(0, _translate("MainWindow", "Double Broom", None))
        self.cmbClasse.setItemText(1, _translate("MainWindow", "Broom", None))
        self.lblFolhas.setText(_translate("MainWindow", "Folhas (k):", None))
        self.lblOrdem.setText(_translate("MainWindow", "Ordem (n):", None))
        self.lblDiametro.setText(_translate("MainWindow", "Diâmetro (d):", None))
        self.btnAdicionarAresta.setText(_translate("MainWindow", "Adicionar Aresta", None))
        self.btnGerarTabela.setText(_translate("MainWindow", "Gerar Tabela...", None))
        self.btnGerarGrafo.setText(_translate("MainWindow", "Gerar Grafo", None))

